require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CsvFilesController do

  # This should return the minimal set of attributes required to create a valid
  # CsvFile. As you add validations to CsvFile, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all csv_files as @csv_files" do
      csv_file = CsvFile.create! valid_attributes
      get :index
      assigns(:csv_files).should eq([csv_file])
    end
  end

  describe "GET show" do
    it "assigns the requested csv_file as @csv_file" do
      csv_file = CsvFile.create! valid_attributes
      get :show, :id => csv_file.id.to_s
      assigns(:csv_file).should eq(csv_file)
    end
  end

  describe "GET new" do
    it "assigns a new csv_file as @csv_file" do
      get :new
      assigns(:csv_file).should be_a_new(CsvFile)
    end
  end

  describe "GET edit" do
    it "assigns the requested csv_file as @csv_file" do
      csv_file = CsvFile.create! valid_attributes
      get :edit, :id => csv_file.id.to_s
      assigns(:csv_file).should eq(csv_file)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CsvFile" do
        expect {
          post :create, :csv_file => valid_attributes
        }.to change(CsvFile, :count).by(1)
      end

      it "assigns a newly created csv_file as @csv_file" do
        post :create, :csv_file => valid_attributes
        assigns(:csv_file).should be_a(CsvFile)
        assigns(:csv_file).should be_persisted
      end

      it "redirects to the created csv_file" do
        post :create, :csv_file => valid_attributes
        response.should redirect_to(CsvFile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved csv_file as @csv_file" do
        # Trigger the behavior that occurs when invalid params are submitted
        CsvFile.any_instance.stub(:save).and_return(false)
        post :create, :csv_file => {}
        assigns(:csv_file).should be_a_new(CsvFile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CsvFile.any_instance.stub(:save).and_return(false)
        post :create, :csv_file => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested csv_file" do
        csv_file = CsvFile.create! valid_attributes
        # Assuming there are no other csv_files in the database, this
        # specifies that the CsvFile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CsvFile.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => csv_file.id, :csv_file => {'these' => 'params'}
      end

      it "assigns the requested csv_file as @csv_file" do
        csv_file = CsvFile.create! valid_attributes
        put :update, :id => csv_file.id, :csv_file => valid_attributes
        assigns(:csv_file).should eq(csv_file)
      end

      it "redirects to the csv_file" do
        csv_file = CsvFile.create! valid_attributes
        put :update, :id => csv_file.id, :csv_file => valid_attributes
        response.should redirect_to(csv_file)
      end
    end

    describe "with invalid params" do
      it "assigns the csv_file as @csv_file" do
        csv_file = CsvFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CsvFile.any_instance.stub(:save).and_return(false)
        put :update, :id => csv_file.id.to_s, :csv_file => {}
        assigns(:csv_file).should eq(csv_file)
      end

      it "re-renders the 'edit' template" do
        csv_file = CsvFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CsvFile.any_instance.stub(:save).and_return(false)
        put :update, :id => csv_file.id.to_s, :csv_file => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested csv_file" do
      csv_file = CsvFile.create! valid_attributes
      expect {
        delete :destroy, :id => csv_file.id.to_s
      }.to change(CsvFile, :count).by(-1)
    end

    it "redirects to the csv_files list" do
      csv_file = CsvFile.create! valid_attributes
      delete :destroy, :id => csv_file.id.to_s
      response.should redirect_to(csv_files_url)
    end
  end

end
