require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IncommingCallsController do

  # This should return the minimal set of attributes required to create a valid
  # IncommingCall. As you add validations to IncommingCall, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all incomming_calls as @incomming_calls" do
      incomming_call = IncommingCall.create! valid_attributes
      get :index
      assigns(:incomming_calls).should eq([incomming_call])
    end
  end

  describe "GET show" do
    it "assigns the requested incomming_call as @incomming_call" do
      incomming_call = IncommingCall.create! valid_attributes
      get :show, :id => incomming_call.id.to_s
      assigns(:incomming_call).should eq(incomming_call)
    end
  end

  describe "GET new" do
    it "assigns a new incomming_call as @incomming_call" do
      get :new
      assigns(:incomming_call).should be_a_new(IncommingCall)
    end
  end

  describe "GET edit" do
    it "assigns the requested incomming_call as @incomming_call" do
      incomming_call = IncommingCall.create! valid_attributes
      get :edit, :id => incomming_call.id.to_s
      assigns(:incomming_call).should eq(incomming_call)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IncommingCall" do
        expect {
          post :create, :incomming_call => valid_attributes
        }.to change(IncommingCall, :count).by(1)
      end

      it "assigns a newly created incomming_call as @incomming_call" do
        post :create, :incomming_call => valid_attributes
        assigns(:incomming_call).should be_a(IncommingCall)
        assigns(:incomming_call).should be_persisted
      end

      it "redirects to the created incomming_call" do
        post :create, :incomming_call => valid_attributes
        response.should redirect_to(IncommingCall.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved incomming_call as @incomming_call" do
        # Trigger the behavior that occurs when invalid params are submitted
        IncommingCall.any_instance.stub(:save).and_return(false)
        post :create, :incomming_call => {}
        assigns(:incomming_call).should be_a_new(IncommingCall)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        IncommingCall.any_instance.stub(:save).and_return(false)
        post :create, :incomming_call => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested incomming_call" do
        incomming_call = IncommingCall.create! valid_attributes
        # Assuming there are no other incomming_calls in the database, this
        # specifies that the IncommingCall created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        IncommingCall.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => incomming_call.id, :incomming_call => {'these' => 'params'}
      end

      it "assigns the requested incomming_call as @incomming_call" do
        incomming_call = IncommingCall.create! valid_attributes
        put :update, :id => incomming_call.id, :incomming_call => valid_attributes
        assigns(:incomming_call).should eq(incomming_call)
      end

      it "redirects to the incomming_call" do
        incomming_call = IncommingCall.create! valid_attributes
        put :update, :id => incomming_call.id, :incomming_call => valid_attributes
        response.should redirect_to(incomming_call)
      end
    end

    describe "with invalid params" do
      it "assigns the incomming_call as @incomming_call" do
        incomming_call = IncommingCall.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IncommingCall.any_instance.stub(:save).and_return(false)
        put :update, :id => incomming_call.id.to_s, :incomming_call => {}
        assigns(:incomming_call).should eq(incomming_call)
      end

      it "re-renders the 'edit' template" do
        incomming_call = IncommingCall.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IncommingCall.any_instance.stub(:save).and_return(false)
        put :update, :id => incomming_call.id.to_s, :incomming_call => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested incomming_call" do
      incomming_call = IncommingCall.create! valid_attributes
      expect {
        delete :destroy, :id => incomming_call.id.to_s
      }.to change(IncommingCall, :count).by(-1)
    end

    it "redirects to the incomming_calls list" do
      incomming_call = IncommingCall.create! valid_attributes
      delete :destroy, :id => incomming_call.id.to_s
      response.should redirect_to(incomming_calls_url)
    end
  end

end
