require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OutgoingCallsController do

  # This should return the minimal set of attributes required to create a valid
  # OutgoingCall. As you add validations to OutgoingCall, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all outgoing_calls as @outgoing_calls" do
      outgoing_call = OutgoingCall.create! valid_attributes
      get :index
      assigns(:outgoing_calls).should eq([outgoing_call])
    end
  end

  describe "GET show" do
    it "assigns the requested outgoing_call as @outgoing_call" do
      outgoing_call = OutgoingCall.create! valid_attributes
      get :show, :id => outgoing_call.id.to_s
      assigns(:outgoing_call).should eq(outgoing_call)
    end
  end

  describe "GET new" do
    it "assigns a new outgoing_call as @outgoing_call" do
      get :new
      assigns(:outgoing_call).should be_a_new(OutgoingCall)
    end
  end

  describe "GET edit" do
    it "assigns the requested outgoing_call as @outgoing_call" do
      outgoing_call = OutgoingCall.create! valid_attributes
      get :edit, :id => outgoing_call.id.to_s
      assigns(:outgoing_call).should eq(outgoing_call)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OutgoingCall" do
        expect {
          post :create, :outgoing_call => valid_attributes
        }.to change(OutgoingCall, :count).by(1)
      end

      it "assigns a newly created outgoing_call as @outgoing_call" do
        post :create, :outgoing_call => valid_attributes
        assigns(:outgoing_call).should be_a(OutgoingCall)
        assigns(:outgoing_call).should be_persisted
      end

      it "redirects to the created outgoing_call" do
        post :create, :outgoing_call => valid_attributes
        response.should redirect_to(OutgoingCall.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved outgoing_call as @outgoing_call" do
        # Trigger the behavior that occurs when invalid params are submitted
        OutgoingCall.any_instance.stub(:save).and_return(false)
        post :create, :outgoing_call => {}
        assigns(:outgoing_call).should be_a_new(OutgoingCall)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OutgoingCall.any_instance.stub(:save).and_return(false)
        post :create, :outgoing_call => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested outgoing_call" do
        outgoing_call = OutgoingCall.create! valid_attributes
        # Assuming there are no other outgoing_calls in the database, this
        # specifies that the OutgoingCall created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OutgoingCall.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => outgoing_call.id, :outgoing_call => {'these' => 'params'}
      end

      it "assigns the requested outgoing_call as @outgoing_call" do
        outgoing_call = OutgoingCall.create! valid_attributes
        put :update, :id => outgoing_call.id, :outgoing_call => valid_attributes
        assigns(:outgoing_call).should eq(outgoing_call)
      end

      it "redirects to the outgoing_call" do
        outgoing_call = OutgoingCall.create! valid_attributes
        put :update, :id => outgoing_call.id, :outgoing_call => valid_attributes
        response.should redirect_to(outgoing_call)
      end
    end

    describe "with invalid params" do
      it "assigns the outgoing_call as @outgoing_call" do
        outgoing_call = OutgoingCall.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OutgoingCall.any_instance.stub(:save).and_return(false)
        put :update, :id => outgoing_call.id.to_s, :outgoing_call => {}
        assigns(:outgoing_call).should eq(outgoing_call)
      end

      it "re-renders the 'edit' template" do
        outgoing_call = OutgoingCall.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OutgoingCall.any_instance.stub(:save).and_return(false)
        put :update, :id => outgoing_call.id.to_s, :outgoing_call => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested outgoing_call" do
      outgoing_call = OutgoingCall.create! valid_attributes
      expect {
        delete :destroy, :id => outgoing_call.id.to_s
      }.to change(OutgoingCall, :count).by(-1)
    end

    it "redirects to the outgoing_calls list" do
      outgoing_call = OutgoingCall.create! valid_attributes
      delete :destroy, :id => outgoing_call.id.to_s
      response.should redirect_to(outgoing_calls_url)
    end
  end

end
